# THIS SQL SCRIPT CREATES USER TABLE IN HELBERTON DATABASE
CREATE DATABASE IF NOT EXISTS holberton;
USE holberton;
DROP TABLE users;
CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255)
);
